export interface IObservation {
  key: string
  class: string
  expire_time_gmt: number
  obs_id: string
  obs_name: string
  valid_time_gmt: number
  day_ind: string
  temp: number
  wx_icon: any
  icon_extd: any
  wx_phrase: any
  pressure_tend: number
  pressure_desc: string
  dewPt: number
  heat_index: number
  rh: number
  pressure: number
  vis: any
  wc: number
  wdir: number
  wdir_cardinal: string
  gust: number
  wspd: number
  max_temp: any
  min_temp: any
  precip_total: any
  precip_hrly: any
  snow_hrly: any
  uv_desc: string
  feels_like: number
  uv_index: number
  qualifier: any
  qualifier_svrty: any
  blunt_phrase: any
  terse_phrase: any
  clds: any
  water_temp: any
  primary_wave_period: any
  primary_wave_height: any
  primary_swell_period: any
  primary_swell_height: any
  primary_swell_direction: any
  secondary_swell_period: any
  secondary_swell_height: any
  secondary_swell_direction: any
}
