name: Testing

on: [pull_request]

jobs:
  test:
    name: Unit tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16.18.0

      - name: Install dependencies
        run: yarn install

      - name: Build
        run: yarn run build

      - name: Run tests
        run: yarn run test